### ISSUE TITLE
Activating 2 wireless cards

### ISSUE THREAD

**Issue by 1974darrenh** [sophron/wifiphisher#181]
Hi.

I understand that to use this program, I need 2 wireless cards.

I have a TP-Link TL-WN722N which is capable of doing the packet injections etc, plugged into the USB socket. I also have the internal wireless card in the laptop but I don't know how to set them to both run on Kali. When I start Wifiphisher it always says "Only one wireless interface found. Closing..." It is only picking up the TP-Link. How do I set it up to work because I am struggling to find instructions.

Requirements

    Kali Linux.
    Two wireless network interfaces, one capable of injection

Thanks.

**Comment by mojojojojo** [comment]
Im not certain, but I believe you have to buy one more wireless card. I had your problem and got one more and I dont see that error anymore.

**Comment by 1974darrenh** [comment]
I've read about other people using their internal card and external USB one together, just cant figure it out.

**Comment by blackHatMonkey** [comment]
Are you using a virtual machine or running kali natively?

**Comment by 1974darrenh** [comment]
VMware Workstation. I have solved the problem by buying another USB adapter. 

However......I attempted to attack my own network. Wifiphisher looked to be doing what it should but my network was fully accessible with no jamming or router page displaying, so for some reason it is not working at all :(

**Comment by blackHatMonkey** [comment]
Did ```Wifiphisher``` create another access point with the same name but open?

**Comment by 1974darrenh** [comment]
Can't see one.

**Comment by blackHatMonkey** [comment]
yes, I'd had the same problem. You may want to try this [version](https://github.com/sophron/wifiphisher/releases/tag/v1.1).

**Comment by 1974darrenh** [comment]
Ok. Update.

Yes it is producing an open identical AP however....it is not deauthenticating connecting computers or blocking internet access. Therefore the open network seems pointless.

I must be doing something wrong :(

**Comment by 1974darrenh** [comment]
My equipment-
(1st wireless) TP-LINK TL-WN722N for injection etc

(2nd wireless) TP-LINK TL-WN823N

How can I be sure that wifiphisher is using the TL-WN722N for doing the injecting and not the other one?

**Comment by blackHatMonkey** [comment]
The point of the tool is to fish the wifi password from the user instead of cracking the password using brute force. The tool cannot block internet on the original access point and it simply starts to de-authenticate the users on the network.  The user has to select the fake access point that was created manually.

**Comment by blackHatMonkey** [comment]
You can use the command line options -aI -jI. Please see usage in Readme.

**Comment by frafrichile** [comment]
can you give me two working cards? I have Alfa pairs but they don't work I think

**Comment by frafrichile** [comment]
I have the same problem and I tried the other version as suggested by @blackHatMonkey . It creates a opened access point with the same name but unsecured. After a little it dissapears and while testing I am still able to browse the internet as usual .

**Comment by blackHatMonkey** [comment]
@frafrichile 

The unsecured access point is what the ```wifiphisher``` is suppose to do. When it dissapers is ```wifiphisher``` still running in terminal. If you have correctly connected to the access point you shouldn't be able to have access to the internet and you should only see the minimal page. Can you try with the latest version and report back?

**Comment by frafrichile** [comment]
@blackHatMonkey  okay so this is my set up . Windows 10, VirtualBox . Kali Sana

phy0	 wlan0		rtl8187		Realtek Semiconductor Corp. RTL8187 (AWUS036H)

phy1	 wlan1		rtl8192cu	Edimax Technology Co., Ltd EW-7811Un 802.11n [Realtek RTL8188CUS] 

I used the wifiphiser-master

and this was my code

<code> ./wifiphisher.py -aI wlan1 <code>

It did succesfully create an access point . an open network but it failed to obtain an IP address from my phone ( Galaxy s6 edge ) and from my windows 10 machine it connected but it did not present me with any pages.

for some reason the AWUS036NHA driver is acting weird on windows 10 ( known issue) so instead I used my N-150 Edimax. Which did the job because it prevented me from connecting to my network
![screenshot_2015-12-09-17-55-46](https://cloud.githubusercontent.com/assets/6171920/11702861/bc1b2a42-9e9f-11e5-970f-fefc8a7c9a38.png)

**Comment by blackHatMonkey** [comment]
@frafrichile 
>./wifiphisher.py -aI wlan1

I'm sure this is just a typo because it's suppose to be
```bash
$ sudo python wifiphisher.py -aI wlan1
```
Take a look at this [video](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=1&cad=rja&uact=8&ved=0ahUKEwicgJrXgNDJAhWFFh4KHSJ6BOMQtwIIHDAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DK1ETBeRQBs4&usg=AFQjCNH4cXsDFM7vnxxrKPOX_oD5hjsAmA) and set  up wireless adapters like the video in the virtualbox.
Run the fallowing commands:
```bash
$ nmcli radio wifi off

$ ifconfig -a
```
you must be able to see two wireless adapters.
after that run these commands and replace wlx with the two adapters from above:
```bash
$ ifconfig wlx up
$ ifconfig wlx up
```
At this point the lights on the alfa must be blinking (ON).
Then you can ```wifiphisher```
```bash
$ sudo python wifiphisher.py -aI wlan1
```
Let me know if that solves you problem.

**Comment by frafrichile** [comment]
@blackHatMonkey Okay so after doing the same thing I was doing 3 times. It worked! but this time it did not jam the wireless( so i had to disconnect and connect manually) . I am going to try with what you suggested now. and see if that makes a difference

**Comment by frafrichile** [comment]
@blackHatMonkey I did all the above but for some reason it is not jamming my AP .

**Comment by blackHatMonkey** [comment]
This seems to be a bug and I'm sure it will get fixed soon. Just wondering which card is the ```wlan1```?

**Comment by frafrichile** [comment]
@blackHatMonkey 
Edimax EW-7811Un
http://www.amazon.com/Edimax-EW-7811Un-150Mbps-Raspberry-Supports/dp/B003MTTJOY

**Comment by blackHatMonkey** [comment]
@frafrichile 

Can you post the output of these commands
```bash
$ sudo iw dev
```
the output should resemble
```bash
phy#x
```
put ```x``` in
```bash
iw phy phy(x) info
```

**Comment by frafrichile** [comment]
phy#1
	Interface wlan0
		ifindex 4
		wdev 0x100000001
		addr 00:c0:ca:81:8d:cf
		type managed
phy#0
	Interface wlan1
		ifindex 3
		wdev 0x1
		addr 80:1f:02:bf:1d:7d
		type managed

for phy1 http://pastebin.com/Hc9QaR5Z
for phy0 http://pastebin.com/zcEevQXc

**Comment by blackHatMonkey** [comment]
@frafrichile 
Thank you. :+1:

**Comment by 1974darrenh** [comment]
The problem I have is that I can see the fake AP but can still connect through the original AP, so in other words, It's not jamming or de-authenticating my AP at all.

What am I doing wrong?

**Comment by blackHatMonkey** [comment]
You may want to try giving ```wifiphisher``` the ```-jI``` flag and see if it de-authenticates or not. However there definitely is a bug regarding jamming or creating an ```AP```.

**Comment by 1974darrenh** [comment]
Ok thanks :)

**Comment by blackHatMonkey** [comment]
The issue should be solved now. If you still experience any issues after upgrading to the latest version feel free to open a new issue.
