### ISSUE TITLE
Template to serve payloads to targets

### ISSUE THREAD

**Issue by P5I** [sophron/wifiphisher#216]
I've been playing around with this a lot and recently used it to serve a payload to a target.
It adds another attack vector aside from phishing alone :)

I've attached the template I've been using. Just replace the **payload_File** with a payload/executable you want to serve to a target, select the template, and run the tool.

[adobe.zip](https://github.com/sophron/wifiphisher/files/155365/adobe.zip)

**Comment by sophron** [comment]
@P5I, nice! We definitely want to include this. Do you think you can <a href="https://help.github.com/articles/creating-a-pull-request/"> submit a PR</a>?

Also, by the name of the zip file, I can tell that the template of this scenario has to do with Adobe. Unfortunately, we can't contain any third-party material (such as logos or proprietary templates) due to copyright reasons. That means, that we have to make the template generic and not associated with any organization/company. Keep that in mind, if you planning to submit a PR.

Thanks for contributing.

**Comment by P5I** [comment]
@sophron, my mistake, I posted this before reading the template submission guidelines. Glad you like the idea though.

I'll work on designing a generic payload download template and submit a PR when I'm done.

**Comment by sophron** [comment]
Great, thanks.

**Comment by sophron** [comment]
#229 implemented this.
