### ISSUE TITLE
The victim can detect wifiphisher

### ISSUE THREAD

**Issue by Anonymous0Libya** [sophron/wifiphisher#275]
HI, can anyone can fix this problem ..? ... i tried wifiphisher at router and then i got a message saying that my page is not safe ..... but every thing is working fine ... but i think that if u would make it undetected to the victim's device... Thank you ....

**Comment by blackHatMonkey** [comment]
Hi @Anonymous0Libya 
Since `wifiphisher` uses a self-signed certificate some browser will show you the not safe page. However that only happens when your browser already holds the certificate of a domain. For instance if you try to go to `www.google.com` it will show you that page but not on `www.thisisjustatest.com`.

**Comment by sophron** [comment]
This is how SSL works. It has nothing to do with detection of the tool.
