### ISSUE TITLE
What is the expected behavior?

### ISSUE THREAD

**Issue by erawtfos78** [sophron/wifiphisher#277]
commit 0bc2a82b805ab0502cd1e8b313984b5880e46b5b

Kali Linux Rolling 2016.1

Expected behavior?

I've been working with the tool for a some weeks now.  When my ap is targeted, what I end up with is two available access points.  One is my normal access point which we'll call 'nowire' which in Windows shows as 'Secured'.  This is normal and completely fine as this is what I use to connect to and browse the internet on a daily basis.  The second access point that gets created is is also called no 'nowire' but within Windows shows as 'Open'.  This is the ap I'm assuming the tool has copied and waits for connections.  

My question is, should I see both the secured connection (my normal connection) and then a fake ap as well for the tool to work properly?  Or should the tool assume the normal connection and only one by the name 'nowire' be present?

My assumption was that the tool would take over the ap, force a reconnection to the tool's created ap, and at that time would get prompted to select the router plugin page for example.  

Clarification would be very helpful.  

**Comment by blackHatMonkey** [comment]
Hi @erawtfos78 
How the `wifiphisher` works is that it creates an identical copy of the targeted access point but it's security type is set to `open`. So if you are able to see two access points with the same name while having different security types `wifiphisher` is working properly. The concept behind `wifiphisher` is that it starts de-authenticating all the devices connected to the target access point. Depending on the operating system and network manager it might fully disconnect and show a list of all the available networks and we **hope** that the user selects our access point instead of the real one. As it is with all the phishing tools, you can only hope that the user makes a mistake and you can capitalize on it.

I hope that clear it up. If you have more question don't hesitate to ask.

**Comment by sophron** [comment]
@blackHatMonkey correctly commented the scenario where we target a password-protected network.

However, in scenarios where we target open networks or networks with disclosed PSKs (e.g. airports or hotels), the encryption setting will be the same and victims will automatically connect to the rogue AP.

I'll planning to publish a paper soon enough that will clarify in detail all possible attack scenarios.

**Comment by wraith-wireless** [comment]
Looking forward to that white paper - will be an interesting read

**Comment by erawtfos78** [comment]
That is very helpful.  Thank you.  The tool is working as intended in my scenario then.  I would only add in regards to your statement, "The concept behind wifiphisher is that **it starts de-authenticating all the devices connected to the target access point**. **Depending on the operating system and network manager it might fully disconnect and show a list of all the available networks and we hope that the user selects our access point instead of the real one.**  Is it others experience as well where it seems that the Windows OS network manager seems to just reconnect to original ap.  iOS seems to have a bit more trouble in that regard.  Is there a way to make the deauth more effective or is this just a limitation in regards to distance and how the various network managers re-connect one deauth'ed?  Thanks for your responses and all who contribute.
