### ISSUE TITLE
Create a fake ESSID and put some spaces after it.

### ISSUE THREAD

**Issue by djdisikd** [sophron/wifiphisher#356]
Example this is the Wifi that we want to deauthenticate 

ESSID (Wifi network name) : Hello

Can we copy the same ESSID (network name) and create a open Wifi network with some space after the ESSID (network name)?

That means the ESSID (Wifi network name) should be Hello and then put some space after it.

People will see two wifi networks (Hello) instead of one.

I think this is a great idea and people won't realize it.

**Comment by sophron** [comment]
Hi @djdisikd,

If we target a password protected network and we don't know the pre-shared key, the Evil Twin will be an open network. Network managers will display this as a second (different) network even though they share the same ESSID (because they have different encryption settings).

If we target an open network or a password protected network that we know the pre-shared key, the Evil Twin will be a very exact replica of the target. In that case, network managers will display only *one* network. But this is not an issue. An attacker with a stronger signal can still attract victims to the rogue Access Point.

There is a case however, where this makes sense, and this is when using WPS-PBC technique (#264) against Windows users. I am planning to write a more detailed article about this attack in the near future.

**Comment by djdisikd** [comment]
Can you add an option for increase wireless adapter signal strength for our convenience?

**Comment by sophron** [comment]
You may change your Wi-Fi card's TX power. There are many tutorials on the Internet that tell you how to do that.

**Comment by djdisikd** [comment]
I think my alfa network adapter does not support increasing TX power. -_-
It doesn't increasing the TX power...

**Comment by djdisikd** [comment]
The victim will detect our (fake) wifi even if the signal strength is low.

**Comment by sophron** [comment]
I am not sure I understand your claim.

**Comment by djdisikd** [comment]
Which you do not understand?
