### ISSUE TITLE
idea for UI

### ISSUE THREAD

**Issue by gregory** [sophron/wifiphisher#44]
what about a way to fetch the real router config page, modify it (i guess update the form's action to point to us) then serve it? 

Might be a more generic solution than designing all the pages of all the existing routers.... Just a thought.

**Comment by Sitebase** [comment]
That would be cool but not possible. Because at the time you show the config page you don't have access to that actual local network.

**Comment by tgalyean** [comment]
There is another open issue to effectively do this. If this tool had the ability to take the AP MAC address and perform a hardware vendor lookup you could change the page displayed. For example if the MAC returned "linksys", that value could then be used to say "since the hardware is linksys, return the linksys page not the default". Likewise this could be used to display just about any router login page.

**Comment by Knwn** [comment]
tgalyean has the right idea. Now we all just have to contribute custom phishing pages from our routers ;)
![att](https://cloud.githubusercontent.com/assets/10487088/5695914/31408a52-997d-11e4-8aa5-0860c78660d4.jpg)

**Comment by sophron** [comment]
Hi @gregory,

As @Sitebase stated this is not possible. You can't fetch the page since you can't actually access the victim's machine.

**Comment by arthurbarros** [comment]
@tgalyean this is already being discussed at #5

**Comment by tgalyean** [comment]
Yep. Saw that.
