### ISSUE TITLE
Error : network un reachable 

### ISSUE THREAD

**Issue by vinod-mehta** [sophron/wifiphisher#59]
1. what kind of 2 interface do we need ?

2. And am using it in laptop so is only my wifi adapter capable of doing this ? if not say me which interface card should i use

**Comment by sophron** [comment]
I'm not sure i understand your questions. You need two wireless cards for the script to work.

**Comment by sandman6578** [comment]
Hey :)
So you need TWO Wifi-Interfaces.
1. one i would recommend you an atheros chip because it is supporting AP-Mode. The Alfa Awus036h with RTL8187L does not support AP-mode.
You need this because you make your first chipset as an AccessPoint where you vics are connecting to.
2. one you have to use an chipset which is supporting Injection for this one the Alfa AWUS036H is a good choice because its stable and jam the fuck out of your vics ;)

Hope i helped you out.
If theres any other question feel free to ask.
Greetz

**Comment by naflan121** [comment]
does Alfa Awus036h  support ap mode?

**Comment by sandman6578** [comment]
Nope
