### ISSUE TITLE
Can not get the pasword

### ISSUE THREAD

**Issue by casperass** [sophron/wifiphisher#99]
Whenever I try phishing my android phone I can't get the password. I can see it DHCP but whenever I search something on the Google it shows it as the password then closes it self.

For instance; After I connected to fake ap, I google "trying123" wifiphisher shows the searching (trying123) as the password.

It doesn't happen all the time but almost half of the trying I get this.

And now I get a strange response:

I googled someting random and I get this

HTTP requests: 
[*] GET 10.0.0.76
[*] POST 10.0.0.76 password=Samsung GT-N7100

It showed model of the phone as password.

And it warns me "security certificate problem"  before redirect the fake ap web page.

I haven't tried this on a computer yet.
________________________________
Wifi adapter: Alfa AWUS036NHA
Chipset: AR9271

**Comment by casperass** [comment]
It keeps telling the smart phone model as the password. I can't use the script.

**Comment by casperass** [comment]
Well, I started to think it's a bug or something like that. Any help?

**Comment by sophron** [comment]
Hi @casperass,

I just committed a fix. Let me know if it now works properly.

**Comment by casperass** [comment]
Hi @sophron 

I tried and it fixed the password problem but it caused sort of bigger problems. It doesn't make the victim connect the FAKE AP automatically. I mean that I'm trying it on my android device. In half of the tryings it doesn't jam the wifi properly. Half of the other tryings it jams very well however it doesn't make victim connect the FAKE AP. I needed to connect manually. And yeah fake ap was closer and stronger then the router.

Also, I tried to reboot router while wifiphisher was on the phishing. It didn't even connect to the fake ap even though there wasn't any alternative option.

But when I connect manually I got the password successfully.

**Comment by sophron** [comment]
Since the password problem is fixed, i'm closing this. 

About your next issues, please have a look at the <a href="https://github.com/sophron/wifiphisher/wiki/Frequently-Asked-Questions-(FAQ)#q3">FAQ "I have no success using the tool / Nobody is connecting to the rogue AP. What am I doing wrong?"</a>. If you believe you have encountered a bug that has not been reported already, please open a new issue after reading our <a href="https://github.com/sophron/wifiphisher/wiki/Bug-reporting-guidelines">guidelines</a>.
